import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import CodeBlogNavigation from "../../../components/code_blog_navigation";

export const metadata: Metadata = {
  title: "CodeBlog | trainerlee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        <CodeBlogNavigation></CodeBlogNavigation>
        {children}
    </div>
        
  );
}
